### PR TITLE
Corrected the cellml text in the sodium channel tutorial

### PR DESCRIPTION
**Pull request by kerimoyle**
PR to update the text of the sodium_ion_channel.cellml text to reflect the code used to produce the figures, and the equations in the text.

### CODE REVIEW

**Comment by kerimoyle** [comment]
Ready for review/merge please @nickerso @agarny

**Comment by agarny** [comment]
Sorry @kerimoyle, but GitHub doesn't allow me to review your PR. @nickerso, anything that could be done about this?

This aside, the PR looks good, although it would be nice to have a link to the model that is actually used so we can properly review your changes. Right now, we have to "trust" you. :)

**Comment by kerimoyle** [comment]
Haha, you don't have to trust me ... you could just read it the code and compare it to the equations in the text ;)  I just took the code from OpenCOR and copied it here verbatim.  The results from the solver look fine to me (though have used the published initial conditions, not the steady-state starting point which I think was used to create the original figures).  Here's my results: https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/tutorials/tutorial7/tutorial7_cpp.html#run-the-model

**Comment by agarny** [comment]
Ok, also it's mathematically equivalent, there is a slight difference regarding the equation for `alpha_m`. [Here](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/tutorials/tutorial7/tutorial7_cpp.html#create-the-m-gate-component), we have a multiplication by `0.1` while in your PR you have a division by `10`. FWIW, it's computationally more efficient to have a multiplication by `0.1`. Something similar for `alpha_h` and `beta_h`.

Otherwise, in your [RTD](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/tutorials/tutorial7/tutorial7_cpp.html#run-the-model), there is `@SPHINX_YEAR@`...

**Comment by kerimoyle** [comment]
Don't worry about my RTD, they're not ready for review yet, just to show
the outcome of my solver.  The only changes to this PR are taking the code
that's already here and copying the cellml text.  Any efficiencies or other
ways of doing things I haven't looked at at all ...

**Comment by nickerso** [comment]
> Sorry @kerimoyle, but GitHub doesn't allow me to review your PR. @nickerso, anything that could be done about this?

Done. I think :)

**Review by agarny — COMMENTED** [review]
Looks good, just my comment [here](https://github.com/ABI-Tutorials/CellML-OpenCOR-PMR/pull/14#issuecomment-567649527) about the slightly different mathematical formulations.

**Comment by kerimoyle** [comment]
I would have thought that the raw cellml and the cellml text had the same
formulation? I haven't changed anything, just copied the code that was
there to get rid of the mistakes...?

**Comment by agarny** [comment]
> I would have thought that the raw cellml and the cellml text had the same formulation? I haven't changed anything, just copied the code that was there to get rid of the mistakes...?

Not sure I am following you. I am comparing the code in `source/cellml_encaps_and_inter.rst` and `source/resources/sodium_ion_channel.cellml` (actually, why `.cellml` since it's actually a CellML Text representation of a real CellML file) with what I can see [here](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/tutorials/tutorial7/tutorial7_cpp.html#create-the-m-gate-component) and [here](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/tutorials/tutorial7/tutorial7_cpp.html#create-the-h-gate-component).

**Comment by nickerso** [comment]
I think need to compare to the models linked to from the tutorial rather than the libCellML tutorials that @kerimoyle is working on. e.g., via the OpenCOR link in the figure caption...

**Comment by agarny** [comment]
Agreed with @nickerso, but what is that model? Is it [../resources/tutorial7_SodiumChannelModel.cellml](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/_downloads/89479e7da7bef2d164447e23ebb8ef73/tutorial7_SodiumChannelModel.cellml)? That's the only reference I could find on [RTD](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/tutorials/tutorial7/tutorial7_cpp.html#run-the-model). If so, then it would be nice to have that CellML file reformatted. It makes it unnecessarily difficult to check its math.

**Comment by nickerso** [comment]
This is the one from #13. It is given as an OpenCOR link in the figure caption at https://tutorial-on-cellml-opencor-and-pmr.readthedocs.io/en/latest/cellml_encaps_and_inter.html - which links through to  this [SED-ML](https://models.physiomeproject.org/workspace/25d/rawfile/31aa609fc5a976bb65b2803a4bc24776d4ef612b/sodium_ion_channel.sedml), which is in this PMR [workspace](https://models.physiomeproject.org/workspace/25d). Which ends up with this version of the HH sodium channel: https://models.physiomeproject.org/e/430/sodium_ion_channel.cellml/view.

**Comment by agarny** [comment]
Thanks @nickerso, it looks good to me then.

**Review by agarny — APPROVED** [review]

**Pull request merged**
